import { HOME_WEBAPP_ENV, HOME_API_ENV } from '@/config/pageConfigs'

const svnUrl = import.meta.env.VITE_SVN_URL

export function generateHomeMarkdown() {
  const webappEnv = HOME_WEBAPP_ENV
  const apiEnv = HOME_API_ENV

  const envTable = (rows) => {
    const parts = ['| Variable | Descripción | Ejemplo | Estado |', '|---|---|---|---|']
    rows.forEach((r) => {
      const example = r.example ? ('`' + r.example + '`') : '\u2014'
      const status = r.required === false ? 'opcional' : 'requerido'
      parts.push('| `' + r.name + '` | ' + r.description + ' | ' + example + ' | ' + status + ' |')
    })
    return parts.join('\n')
  }

  const sections = []

  sections.push('# BaseKit \u2014 Documentaci\u00f3n de configuraci\u00f3n')
  sections.push('')
  sections.push('> Generado autom\u00e1ticamente desde la pantalla de inicio de BaseKit.')
  sections.push('')
  sections.push('---')
  sections.push('')

  if (svnUrl) {
    sections.push('## Repositorio SVN')
    sections.push('')
    sections.push('Checkout del repositorio completo:')
    sections.push('')
    sections.push('```sh')
    sections.push('svn checkout ' + svnUrl)
    sections.push('```')
    sections.push('')
  }

  sections.push('## Autenticaci\u00f3n \u2014 Keycloak')
  sections.push('')
  sections.push('La autenticaci\u00f3n est\u00e1 basada en **Keycloak 26.5.6**.')
  sections.push('Para desarrollo hay un servidor Keycloak disponible en: **http://192.168.13.162:8080/**.')
  sections.push('Si prefieres usar una instancia propia, instala y configura Keycloak antes de arrancar la aplicaci\u00f3n.')
  sections.push('')
  sections.push('| | |')
  sections.push('|---|---|')
  sections.push('| Versi\u00f3n requerida | `26.5.6` |')
  sections.push('| Runtime | Quarkus (JVM / Java) |')
  sections.push('')
  sections.push('Descarga: <https://www.keycloak.org/downloads-archive>')
  sections.push('> Buscar la versi\u00f3n `26.5.6` en el listado de versiones anteriores.')
  sections.push('')
  sections.push('> **Nota:** el realm, cliente y roles de Keycloak deben coincidir con las variables `VITE_KEYCLOAK_*` del `.env` de la webapp y las variables `KEYCLOAK_*` del `.env` de la API.')
  sections.push('')
  sections.push('---')
  sections.push('')
  sections.push('## Entorno de desarrollo')
  sections.push('')
  sections.push('### Webapp \u2014 React + Vite en http://192.168.13.162:5173')
  sections.push('')
  sections.push('Posicionarse dentro de la carpeta `webapp` y ejecutar:')
  sections.push('')
  sections.push('```sh')
  sections.push('# npm install')
  sections.push('npm run dev')
  sections.push('```')
  sections.push('')
  sections.push('El proxy de Vite redirige `/api/*` a `http://192.168.13.162:8888` autom\u00e1ticamente.')
  sections.push('')
  sections.push('### API PHP \u2014 servidor built-in en http://0.0.0.0:8888')
  sections.push('')
  sections.push('Posicionarse dentro de la carpeta `api` y ejecutar:')
  sections.push('')
  sections.push('```sh')
  sections.push('# Copiar .env.ONLINE1 como .env.NOMBRE_DE_PC y ajustar credenciales')
  sections.push('php -S 0.0.0.0:8888 index.php')
  sections.push('```')
  sections.push('')
  sections.push('---')
  sections.push('')
  sections.push('## Frontend \u2014 Estilos y recursos')
  sections.push('')
  sections.push('### Stack tecnol\u00f3gico')
  sections.push('')
  sections.push('| Librer\u00eda | Descripci\u00f3n |')
  sections.push('|---|---|')
  sections.push('| React 18 | Componentes y hooks |')
  sections.push('| Vite 5 | Bundler y dev server |')
  sections.push('| Tailwind CSS 3 | Utility-first CSS |')
  sections.push('| React Router v6 | Enrutamiento SPA |')
  sections.push('| Zustand | Estado global |')
  sections.push('| i18next | Internacionalizaci\u00f3n |')
  sections.push('| keycloak-js | Autenticaci\u00f3n SSO |')
  sections.push('| lucide-react | Iconos SVG |')
  sections.push('')
  sections.push('### Estilos')
  sections.push('')
  sections.push('Las clases de Tailwind se configuran en `tailwind.config.js`. El modo oscuro usa la estrategia `class`, gestionado mediante el store de Zustand. Los estilos globales est\u00e1n en `src/index.css`.')
  sections.push('')
  sections.push('### Iconos y favicons')
  sections.push('')
  sections.push('Para generar los iconos de la aplicaci\u00f3n (favicon, iconos PWA, etc.) usar el generador online:')
  sections.push('<https://www.favicon-generator.org/>')
  sections.push('')
  sections.push('> **Importante:** solo reemplazar las im\u00e1genes generadas en `webapp/public/images/`. **No modificar** `manifest.json` ni `browserconfig.xml` \u2014 esos ya est\u00e1n configurados correctamente.')
  sections.push('')
  sections.push('Al ejecutar `npm run build` las im\u00e1genes se despliegan autom\u00e1ticamente a `api/public/images/`.')
  sections.push('')
  sections.push('---')
  sections.push('')
  sections.push('## Base de datos')
  sections.push('')
  sections.push('Descarga un dump completo de la base de datos `basekit` en formato SQL.')
  sections.push('Requiere que `mysqldump` est\u00e9 instalado en el servidor.')
  sections.push('')
  sections.push('**Endpoint:** `GET /api/db-dump`')
  sections.push('')
  sections.push('---')
  sections.push('')
  sections.push('## Webapp \u2014 Variables de entorno')
  sections.push('')
  sections.push('Archivo `webapp/.env.development` para local y `webapp/.env.production` para el build.')
  sections.push('Usar `.env.development.example` como plantilla.')
  sections.push('Todas las variables deben comenzar con `VITE_`.')
  sections.push('')
  sections.push(envTable(webappEnv))
  sections.push('')
  sections.push('---')
  sections.push('')
  sections.push('## API \u2014 Variables de entorno')
  sections.push('')
  sections.push('La API busca el archivo `api/.env` en tiempo de ejecuci\u00f3n.')
  sections.push('El sufijo del archivo debe coincidir con el **nombre del equipo** (hostname):')
  sections.push('`api/.env.ONLINE1`, `api/.env.ONLINE2`, `api/.env.MIPC`')
  sections.push('')
  sections.push('Para activarlo: copiar el archivo correspondiente como `api/.env` y ajustar las credenciales si es necesario.')
  sections.push('')
  sections.push(envTable(apiEnv))
  sections.push('')
  sections.push('---')
  sections.push('')
  sections.push('*Generado el ' + new Date().toLocaleString('es-AR') + '*')

  return sections.join('\n')
}
